Upgrade Vite to fix hot reloading
Upgrade Vite to fix recent hot reloading errors along the lines of:

  ReferenceError: can't access lexical declaration '[...]' before
  initialization
  [hmr] Failed to reload [...]. This could be due to syntax errors or
  importing non-existent modules. (see errors above)